Develop
SIWECOS/siwecos-crawler pull request #7
Opened 2019-06-30 16:03 UTC by y-ates

2019-07-01 07:03 UTC, Lednerb requested changes
Ein zwei Anmerkungen hätte ich da.
Ansonsten: Gute Arbeit.

2019-07-01 07:03 UTC, Lednerb commented on app/Http/Kernel.php
> +            'throttle:60,1',
Bitte noch das throttle entfernen, sonst können maximal 60 Anfragen pro Minute gestellt werden; wir werden die API häufiger ansprechen.

2019-07-01 07:03 UTC, Lednerb commented on app/Http/Requests/ScanStartRequest.php
> + *   This program is distributed in the hope that it will be useful,
Bitte Lizenz in eine `LICENSE` Datei im root-dir anlegen und hier bzw. aus allen weiteren Dateien entfernen.

2019-07-01 07:03 UTC, Lednerb commented on app/Jobs/CrawlerJob.php
> +                            'errorMessage' => $exception->getMessage(),
hier bitte die `errorMessage` noch als TranslatableMessage formatieren.

2019-07-01 07:03 UTC, Lednerb commented on config/scanner.php
> +
Datei von `config/scanner.php` in `config/crawler.php` oder `config/siwecos.php` umbenennen.

2019-07-01 07:03 UTC, Lednerb commented on routes/web.php
> +
Die `web` routen würde ich persönlich entfernen, aber deine Entscheidung. Ggf. Throttle prüfen (dürfe aber keine Probleme machen)

2019-07-02 19:27 UTC, y-ates commented on routes/web.php
> +
Ich lass es erstmal drin.

2019-07-07 07:57 UTC, Lednerb approved these changes

2019-07-14 13:26 UTC, merged